# Change these first
owner: Grinest
repo: uptime

sites:
  # Web's
  - name: Grinest Landing Page
    url: https://grinest.com/
    __dangerous__insecure: true
  - name: Control Tower Web
    url: https://control-tower.grinest.com/
  # API's
  - name: Core API
    url: https://core.api.prd.grinest.com/v1/health/
  - name: Tasks Server API (Celery)
    url: https://tasks-server.api.prd.grinest.com/v1/health/
  - name: Webhooks API
    url: https://webhooks.api.prd.grinest.com/v1/health/
  # Platforms
  - name: Metabase
    url: https://metabase.prd.grinest.com/
  - name: Grafana
    url: https://grafana.prd.grinest.com/

## Workers
#  drivers payments job (Generdor de pagos conducores semanal)
#  sync ampeco data job (ETL datos maestros AMPECO)
#  sync recharging reserv job (Sesiones de carga)
#  sync recharging ses job

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.prd.grinest.com
  # baseUrl: /your-repo-name
  logoUrl: https://grinest.com/wp-content/uploads/2023/11/image-1.svg
  name: Estado de Servicios - Grinest
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Bienvenido al centro de monitoreo de la plataforma de transporte **Grinest**. Aquí puedes consultar el estado operacional de todos nuestros servicios, aplicaciones web y APIs. Los datos se actualizan automáticamente cada 2 minutos para garantizar información precisa y oportuna sobre la disponibilidad de nuestra infraestructura tecnológica.
  navbar:
    - title: Estado de Servicios
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Notificaciones de Slack cuando un servicio está caído
notifications:
  - type: slack
    webhook-url: $NOTIFICATION_SLACK_WEBHOOK_URL

workflowSchedule:
  uptime: "*/2 * * * *"        # Verificar estado cada 2 minutos
  responseTime: "0 */6 * * *"  # Actualizar tiempos de respuesta cada 6 horas
  graphs: "0 0 * * *"          # Generar gráficos diariamente a medianoche
  staticSite: "0 1 * * *"      # Actualizar sitio web diariamente a la 1:00 AM

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
